# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0008_auto_20170613_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=500, null=True)),
                ('TITLE29', models.CharField(max_length=300, null=True)),
                ('TITLE20', models.CharField(max_length=300, null=True)),
                ('CATE', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
