# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0010_auto_20170702_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=500, null=True)),
                ('TITLE29', models.CharField(max_length=300, null=True)),
                ('TITLE20', models.CharField(max_length=300, null=True)),
                ('CATE', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='refercount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=500, null=True)),
                ('RC_YS', models.IntegerField(null=True)),
                ('TRC_YS', models.IntegerField(null=True)),
                ('HISTORYRC', models.IntegerField(null=True)),
                ('HISTORYTRC', models.IntegerField(null=True)),
            ],
        ),
    ]
