# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0011_journals_refercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INSTITUTION', models.CharField(max_length=300, null=True)),
                ('STAFFNAME_CN', models.CharField(max_length=100, null=True)),
                ('STAFFNAME_EN', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
